{% set version = "0.5.1" %}

package:
    name: metacortex
    version: "0.5.1"

source:
  url: https://github.com/SR-Martin/metacortex/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 32cf14e00bc9db95aafcdd7ae7bbcd3e6fd606ee7003572cc00f18431fa1df68

build:
  number: 0
requirements:
    build:
      - make