{% set version = "0.5.1" %}

package:
    name: metacortex
    version: "0.5.1"

source:
    git_rev: 641237d
    git_url: https://github.com/SR-Martin/metacortex

build:
  number: 0
requirements:
    build:
      - make